// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VkTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    int timeout = 2000;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void vk() throws InterruptedException {
        driver.get("https://vk.com/");
        driver.manage().window().setSize(new Dimension(1188, 640));
        driver.findElement(By.id("index_email")).click();
        driver.findElement(By.id("index_email")).sendKeys("USERNAME");
        driver.findElement(By.id("index_pass")).sendKeys("PASSWORD");
        driver.findElement(By.id("index_pass")).sendKeys(Keys.ENTER);
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//span[2]")));
        }
        driver.findElement(By.xpath("//span[2]")).click();
        Thread.sleep(timeout);
        driver.findElement(By.xpath("//li[2]/a/span[2]")).click();
        Thread.sleep(timeout);
        driver.findElement(By.xpath("//li[3]/a/span[2]")).click();
        Thread.sleep(timeout);
        driver.findElement(By.xpath("//li[4]/a/span[2]")).click();
        Thread.sleep(timeout);
        driver.findElement(By.xpath("//li[5]/a/span[2]")).click();
        Thread.sleep(timeout);
        driver.findElement(By.xpath("//*[@id=\"top_profile_link\"]")).click();
        Thread.sleep(timeout);
        driver.findElement(By.xpath("//*[@id=\"top_logout_link\"]")).click();
    }
}
